<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="ja" sourcelanguage="en">
  <context>
    <name>@default</name>
    <message>
      <source>Hexotic_3D_HYPOTHESIS</source>
      <translation>MG-Hexa</translation>
    </message>
    <message>
      <source>Hexotic_3D_TITLE</source>
      <translation>仮定の構成</translation>
    </message>
    <message>
      <source>Hexotic_VISCOUS_LAYERS</source>
      <translation>粘性層</translation>
    </message>
    <message>
      <source>Hexotic_INPUT_SIZE</source>
      <translation>サイズ</translation>
    </message>
    <message>
      <source>Hexotic_INPUT_LEVEL</source>
      <translation>細分化のレベル</translation>
    </message>
    <message>
      <source>Hexotic_MAX_SIZE</source>
      <translation>最大サイズ</translation>
    </message>
    <message>
      <source>Hexotic_MIN_SIZE</source>
      <translation>サイズ分</translation>
    </message>
    <message>
      <source>Hexotic_HEXES_MAX_LEVEL</source>
      <translation>六角形の nb に登録: 最大レベル</translation>
    </message>
    <message>
      <source>Hexotic_HEXES_MIN_LEVEL</source>
      <translation>六角形の nb に登録: レベル分</translation>
    </message>
    <message>
      <source>Hexotic_IGNORE_RIDGES</source>
      <translation>尾根のない滑らかなメッシュを生成します。</translation>
    </message>
    <message>
      <source>Hexotic_INVALID_ELEMENTS</source>
      <translation>無効な要素を許可します。</translation>
    </message>
    <message>
      <source>Hexotic_SHARP_ANGLE_THRESHOLD</source>
      <translation>鋭角度のしきい値</translation>
    </message>
    <message>
      <source>Hexotic_NB_PROC</source>
      <translation>プロセスの数</translation>
    </message>
    <message>
      <source>Hexotic_WORKING_DIR</source>
      <translation>作業ディレクトリ</translation>
    </message>
    <message>
      <source>Hexotic_SELECT_DIR</source>
      <translation>選択します.</translation>
    </message>
    <message>
      <source>Hexotic_VERBOSITY</source>
      <translation>詳細</translation>
    </message>
    <message>
      <source>Hexotic_MAX_MEMORY</source>
      <translation>最大メモリ (MB)</translation>
    </message>
    <message>
      <source>Hexotic_SUBDOMAIN_MESH_MODE</source>
      <translation>サブドメインのメッシュ サイズのモード</translation>
    </message>
    <message>
      <source>Hexotic_SD_MODE_1</source>
      <translation>1 つのドメイン</translation>
    </message>
    <message>
      <source>Hexotic_SD_MODE_2</source>
      <translation>虫歯は無視</translation>
    </message>
    <message>
      <source>Hexotic_SD_MODE_3</source>
      <translation>空洞メッシュ</translation>
    </message>
    <message>
      <source>Hexotic_SD_MODE_4</source>
      <translation>ジオメトリ「マニホールド」</translation>
    </message>
    <message>
      <source>Hexotic_ADVANCED</source>
      <translation>詳細オプション</translation>
    </message>
    <message>
      <source>Hexotic_TEXT_OPTIONS</source>
      <translation>テキストのオプション</translation>
    </message>
    <message>
      <source>Hexotic_ADD</source>
      <translation>追加</translation>
    </message>
    <message>
      <source>Hexotic_REMOVE</source>
      <translation>削除</translation>
    </message>
    <message>
      <source>Hexotic_ENTRY</source>
      <translation>エントリー</translation>
    </message>
    <message>
      <source>Hexotic_NAME</source>
      <translation>名前</translation>
    </message>
    <message>
      <source>Hexotic_SIZE</source>
      <translation>サイズ</translation>
    </message>
    <message>
      <source>Hexotic_SEL_SHAPE</source>
      <translation>形の選択</translation>
    </message>
    <message>
      <source>Hexotic_NULL_LOCAL_SIZE</source>
      <translation>局所サイズとしてゼロは許されていない</translation>
    </message>
    <message>
      <source>Hexotic_NB_LAYERS</source>
      <translation>層数</translation>
    </message>
    <message>
      <source>Hexotic_FIRST_LAYER_SIZE</source>
      <translation>最初の層のサイズ</translation>
    </message>
    <message>
      <source>Hexotic_DIRECTION</source>
      <translation>層の方向</translation>
    </message>
    <message>
      <source>Hexotic_GROWTH</source>
      <translation>成長率</translation>
    </message>
    <message>
      <source>Hexotic_FACES_WITH_LAYERS</source>
      <translation>層の面</translation>
    </message>
    <message>
      <source>Hexotic_IMPRINTED_FACES</source>
      <translation>刻印面</translation>
    </message>
  </context>
</TS>
