//  Copyright (C) 2007-2008  CEA/DEN, EDF R&D
//
//  This library is free software; you can redistribute it and/or
//  modify it under the terms of the GNU Lesser General Public
//  License as published by the Free Software Foundation; either
//  version 2.1 of the License.
//
//  This library is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
//  Lesser General Public License for more details.
//
//  You should have received a copy of the GNU Lesser General Public
//  License along with this library; if not, write to the Free Software
//  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA
//
//  See http://www.salome-platform.org/ or email : webmaster.salome@opencascade.com
//
//  File    : HexoticPlugin_Algorithm.idl
//  Author  : Lioka RAZAFINDRAZAKA (CEA)
//
#ifndef _SMESH_HexoticALGORITHM_IDL_
#define _SMESH_HexoticALGORITHM_IDL_

#include "SMESH_Hypothesis.idl"

/*!
 * HexoticPlugin: interfaces to Hexotic related hypotheses and algorithms
 */
module HexoticPlugin
{
  /*!
   * HexoticPlugin_Hexotic: interface of Hexotic algorithm
   */
  interface HexoticPlugin_Hexotic : SMESH::SMESH_3D_Algo
  {
  };

  /*!
   * HexoticPlugin_Hypothesis: interface of "Hexotic parameters" hypothesis
   */
  interface HexoticPlugin_Hypothesis : SMESH::SMESH_Hypothesis
  {
    void SetHexesMinLevel(in long value);
    long GetHexesMinLevel();

    void SetHexesMaxLevel(in long value);
    long GetHexesMaxLevel();

    void SetHexoticQuadrangles(in boolean value);
    boolean GetHexoticQuadrangles();

    void SetHexoticIgnoreRidges(in boolean value);
    boolean GetHexoticIgnoreRidges();

    void SetHexoticInvalidElements(in boolean value);
    boolean GetHexoticInvalidElements();
   
    void SetHexoticSharpAngleThreshold(in long value);
    long GetHexoticSharpAngleThreshold();
  };
};

#endif
